### ISSUE TITLE
fixed apt install bug on linux mint

### ISSUE THREAD

**Issue by shuaiZend** [rikonaka/katoolin4china#8]
https://github.com/shuaiZend/katoolin4china/commit/0e3324135ec52d599839f6d487c08b3b40b78a4f

**Comment by rikonaka** [comment]
已经把建议的代码改进去了，O(∩_∩)O谢谢，然后因为我发现这个提交的时候我已经改了很多master的代码，所以不能合并了还是O(∩_∩)O谢谢
